[web]
web-server ansible_host=13.127.186.138 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/new-ansible-key

[app]
app-server ansible_host=13.127.192.209 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/new-ansible-key

[db]
db-server ansible_host=13.232.47.184 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/new-ansible-key